/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fh_dortmund.inf.cw.surstwalat.client.game.view;

import de.fh_dortmund.inf.cw.surstwalat.client.MainFrame;
import de.fh_dortmund.inf.cw.surstwalat.client.event.EventHandler;
import de.fh_dortmund.inf.cw.surstwalat.client.event.EventListener;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.DiceInteractEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.InventoryChangedEvent;
import de.fh_dortmund.inf.cw.surstwalat.common.model.Item;
import java.util.List;

/**
 *
 * @author Lars
 */
public class InventoryPanel extends javax.swing.JPanel implements EventListener{

    private ItemPanel[] panels = new ItemPanel[25];
    
    /**
     * Creates new form InventoryPanel
     */
    public InventoryPanel() {
        initComponents();
        for(int i = 0; i < 25; i++) {
            ItemPanel ip = new ItemPanel();
            panels[i] = ip;
            itemPanels.add(ip);
        }
        MainFrame.getInstance().getEventManager().registerListener(this);
    }

    @EventHandler
    public void updateInventory(InventoryChangedEvent e) {
        List<Item> inventar = MainFrame.getInstance().getInventar();
        for(int i = 0; i < 25; i++) {
            if(i < inventar.size()) {
                panels[i].setItem(inventar.get(i));
            } else {
                panels[i].setItem(null);
            }
            panels[i].revalidate();
        }
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemPanels = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        itemPanels.setMinimumSize(new java.awt.Dimension(150, 150));
        itemPanels.setLayout(new java.awt.GridLayout(5, 5));
        add(itemPanels, java.awt.BorderLayout.CENTER);

        jButton1.setText("Normaler Würfel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        MainFrame.getInstance().getEventManager().fireEvent(new DiceInteractEvent(null));
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemPanels;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
