/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fh_dortmund.inf.cw.surstwalat.client.game.view;

import de.fh_dortmund.inf.cw.surstwalat.client.FortDayEventMessageListener;
import de.fh_dortmund.inf.cw.surstwalat.client.MainFrame;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.AssignActivePlayerEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.AssignPlayerEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.EliminatePlayerEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.GameCreatedEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.GameStartedEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.ItemAddToUserEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.ItemSpawnEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.PlayerOnFieldMessage;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.PlayerRollEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.SetTokenHealthEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.StartRoundEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.TokenCreatedEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.TokenDeathEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.UpdateZoneEvent;
import de.fh_dortmund.inf.cw.surstwalat.client.event.events.UserJoinGameEvent;
import de.fh_dortmund.inf.cw.surstwalat.common.PropertyType;
import static de.fh_dortmund.inf.cw.surstwalat.common.PropertyType.*;
import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jms.JMSException;
import javax.jms.ObjectMessage;

/**
 *
 * @author Lars
 */
public class Workaround extends javax.swing.JFrame {

    /**
     * Creates new form Workaround
     */
    public Workaround() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));

        jButton1.setText("AssignActivePlayer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("AssignPlayer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("EliminatePlayer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("GameCreated");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("GameStarted");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setText("ItemAddToUser");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setText("ItemSpawn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton9.setText("PlayerOnField");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButton10.setText("PlayerRoll");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);

        jButton11.setText("SetTokenHealth");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);

        jButton12.setText("StartRound");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);

        jButton13.setText("TokenCreated");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);

        jButton14.setText("TokenDeath");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);

        jButton15.setText("UpdateZone");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);

        jButton16.setText("UserJoinGame");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(0, 8));

        jLabel1.setText("gameID");
        jPanel2.add(jLabel1);

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);

        jLabel2.setText("playerID");
        jPanel2.add(jLabel2);

        jTextField2.setText("jTextField2");
        jPanel2.add(jTextField2);

        jLabel3.setText("displayMessage");
        jPanel2.add(jLabel3);

        jTextField3.setText("jTextField3");
        jPanel2.add(jTextField3);

        jLabel4.setText("playerNr");
        jPanel2.add(jLabel4);

        jTextField4.setText("jTextField4");
        jPanel2.add(jTextField4);

        jLabel5.setText("userID");
        jPanel2.add(jLabel5);

        jTextField5.setText("jTextField5");
        jPanel2.add(jTextField5);

        jLabel6.setText("fieldsize");
        jPanel2.add(jLabel6);

        jTextField6.setText("jTextField6");
        jPanel2.add(jTextField6);

        jLabel7.setText("Item");
        jPanel2.add(jLabel7);

        jTextField7.setText("jTextField7");
        jPanel2.add(jTextField7);

        jLabel8.setText("itemID");
        jPanel2.add(jLabel8);

        jTextField8.setText("jTextField8");
        jPanel2.add(jTextField8);

        jLabel9.setText("itempos");
        jPanel2.add(jLabel9);

        jTextField9.setText("jTextField9");
        jPanel2.add(jTextField9);

        jLabel10.setText("tokenID");
        jPanel2.add(jLabel10);

        jTextField10.setText("jTextField10");
        jPanel2.add(jTextField10);

        jLabel11.setText("field");
        jPanel2.add(jLabel11);

        jTextField11.setText("jTextField11");
        jPanel2.add(jTextField11);

        jLabel12.setText("number");
        jPanel2.add(jLabel12);

        jTextField12.setText("jTextField12");
        jPanel2.add(jTextField12);

        jLabel13.setText("health");
        jPanel2.add(jLabel13);

        jTextField13.setText("jTextField13");
        jPanel2.add(jTextField13);

        jLabel14.setText("round");
        jPanel2.add(jLabel14);

        jTextField14.setText("jTextField14");
        jPanel2.add(jTextField14);

        jLabel15.setText("tokens");
        jPanel2.add(jLabel15);

        jTextField15.setText("jTextField15");
        jPanel2.add(jTextField15);

        jLabel16.setText("zoneBegin");
        jPanel2.add(jLabel16);

        jTextField16.setText("jTextField16");
        jPanel2.add(jTextField16);

        jLabel17.setText("zoneSize");
        jPanel2.add(jLabel17);

        jTextField17.setText("jTextField17");
        jPanel2.add(jTextField17);

        jLabel18.setText("nextZoneBegin");
        jPanel2.add(jLabel18);

        jTextField18.setText("jTextField18");
        jPanel2.add(jTextField18);

        jLabel19.setText("nextZoneSize");
        jPanel2.add(jLabel19);

        jTextField19.setText("jTextField19");
        jPanel2.add(jTextField19);

        jLabel20.setText("damage");
        jPanel2.add(jLabel20);

        jTextField20.setText("jTextField20");
        jPanel2.add(jTextField20);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get1());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get2());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get3());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get4());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get5());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get6());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get7());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get8());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get9());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get10());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get11());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get12());
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get13());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get14());
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        MainFrame.getInstance().getEventManager().fireEvent(get15());
    }//GEN-LAST:event_jButton16ActionPerformed

    public AssignActivePlayerEvent get1() {
        ObjectMessage o = getMsg(PLAYER_NO);
        setInt(o, GAME_ID, gameID());
        setInt(o, PLAYER_ID, playerID());
        setString(o, DISPLAY_MESSAGE, displayMessage());
        try {
            return new AssignActivePlayerEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public AssignPlayerEvent get2() {
        ObjectMessage o = getMsg(playerNr());
        setInt(o, GAME_ID, gameID());
        setInt(o, PLAYER_ID, playerID());
        setInt(o, USER_ID, userID());
        try {
            return new AssignPlayerEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public EliminatePlayerEvent get3() {
        ObjectMessage o = getMsg(PLAYER_NO);
        setInt(o, GAME_ID, gameID());
        setInt(o, PLAYER_ID, playerID());
        setString(o, DISPLAY_MESSAGE, displayMessage());
        try {
            return new EliminatePlayerEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public GameCreatedEvent get4() {
        ObjectMessage o = getMsg();
        setInt(o, GAME_ID, gameID());
        setInt(o, USER_ID, userID());
        try {
            return new GameCreatedEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public GameStartedEvent get5() {
        ObjectMessage o = getMsg();
        setInt(o, GAME_ID, gameID());
        setString(o, DISPLAY_MESSAGE, displayMessage());
        setInt(o, GAME_FIELDSIZE, fieldsize());
        try {
            return new GameStartedEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public ItemAddToUserEvent get6() {
        ObjectMessage o = getMsg(item());
        setInt(o, GAME_ID, gameID());
        setInt(o, PLAYER_ID, playerID());
        try {
            return new ItemAddToUserEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public ItemSpawnEvent get7() {
        ObjectMessage o = getMsg(item());
        setInt(o, GAME_ID, gameID());
        setInt(o, ITEM_ID, itemid());
        setInt(o, ITEM_POS, itempos());
        try {
            return new ItemSpawnEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public PlayerOnFieldMessage get8() {
        ObjectMessage o = getMsg();
        setInt(o, GAME_ID, gameID());
        setInt(o, PLAYER_ID, playerID());
        setInt(o, TOKEN_ID, tokenid());
        setInt(o, FIELD_ID, field());
        try {
            return new PlayerOnFieldMessage(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public PlayerRollEvent get9() {
        ObjectMessage o = getMsg(number());
        setInt(o, GAME_ID, gameID());
        setString(o, DISPLAY_MESSAGE, displayMessage());
        setInt(o, PLAYER_NO, playerNr());
        try {
            return new PlayerRollEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public SetTokenHealthEvent get10() {
        ObjectMessage o = getMsg();
        setInt(o, GAME_ID, gameID());
        setInt(o, TOKEN_ID, tokenid());
        setInt(o, HEALTH, health());
        try {
            return new SetTokenHealthEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public StartRoundEvent get11() {
        ObjectMessage o = getMsg(round());
        setInt(o, GAME_ID, gameID());
        setString(o, DISPLAY_MESSAGE, displayMessage());
        try {
            return new StartRoundEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public TokenCreatedEvent get12() {
        ObjectMessage o = getMsg(tokens());
        setInt(o, PLAYER_ID, playerID());
        setInt(o, PLAYER_NO, playerNr());
        setInt(o, GAME_ID, gameID());
        try {
            return new TokenCreatedEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public TokenDeathEvent get13() {
        ObjectMessage o = getMsg();
        setInt(o, GAME_ID, gameID());
        setInt(o, TOKEN_ID, tokenid());
        try {
            return new TokenDeathEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public UpdateZoneEvent get14() {
        ObjectMessage o = getMsg();
        setInt(o, GAME_ID, gameID());
        setInt(o, CURRENT_ZONE_BEGIN, zoneBegin());
        setInt(o, CURRENT_ZONE_SIZE, zoneSize());
        setInt(o, NEXT_ZONE_BEGIN, nextZoneBegin());
        setInt(o, NEXT_ZONE_SIZE, nextZoneSize());
        setString(o, DISPLAY_MESSAGE, displayMessage());
        setInt(o, DAMAGE, damage());
        try {
            return new UpdateZoneEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public UserJoinGameEvent get15() {
        ObjectMessage o = getMsg();
        setInt(o, GAME_ID, gameID());
        setInt(o, USER_ID, userID());
        try {
            return new UserJoinGameEvent(o);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public int gameID() {
        return Integer.parseInt(jTextField1.getText());
    }
    
    public int playerID() {
        return Integer.parseInt(jTextField2.getText());
    }
    
    public String displayMessage() {
        return jTextField3.getText();
    }
    
    public int playerNr() {
        return Integer.parseInt(jTextField4.getText());
    }
    
    public int userID() {
        return Integer.parseInt(jTextField5.getText());
    }
    
    public int fieldsize() {
        return Integer.parseInt(jTextField6.getText());
    }
    
    public int item() {
        return Integer.parseInt(jTextField7.getText());
    }
    
    public int itemid() {
        return Integer.parseInt(jTextField8.getText());
    }
    
    public int itempos() {
        return Integer.parseInt(jTextField9.getText());
    }
    
    public int tokenid() {
        return Integer.parseInt(jTextField10.getText());
    }
    
    public int field() {
        return Integer.parseInt(jTextField11.getText());
    }
    
    public int number() {
        return Integer.parseInt(jTextField12.getText());
    }
    
    public int health() {
        return Integer.parseInt(jTextField13.getText());
    }
    
    public int round() {
        return Integer.parseInt(jTextField14.getText());
    }
    
    public LinkedList<Integer> tokens() {
        String[] tokens = jTextField15.getText().split(",");
        LinkedList<Integer> result = new LinkedList<>();
        for(String s:tokens) {
            result.add(Integer.parseInt(s));
        }
        return result;
    }
    
    public int zoneBegin() {
        return Integer.parseInt(jTextField16.getText());
    }
    
    public int zoneSize() {
        return Integer.parseInt(jTextField17.getText());
    }
    
    public int nextZoneBegin() {
        return Integer.parseInt(jTextField18.getText());
    }
    
    public int nextZoneSize() {
        return Integer.parseInt(jTextField19.getText());
    }
    
    public int damage() {
        return Integer.parseInt(jTextField20.getText());
    }
    
    public ObjectMessage getMsg(Serializable o) {
        return FortDayEventMessageListener.getInstance(null).getMsg(o);
    }
    
    public ObjectMessage getMsg() {
        return FortDayEventMessageListener.getInstance(null).getMsg();
    }
    
    public void setInt(ObjectMessage o, String name, int value) {
        try {
            o.setIntProperty(name, value);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setString(ObjectMessage o, String name, String value) {
        try {
            o.setStringProperty(name, value);
        } catch (JMSException ex) {
            Logger.getLogger(Workaround.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workaround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workaround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workaround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workaround.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workaround().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
