package de.fh_dortmund.inf.cw.surstwalat.client.user.view;

import de.fh_dortmund.inf.cw.surstwalat.client.MainFrame;
import de.fh_dortmund.inf.cw.surstwalat.client.game.view.MainPanel;
import de.fh_dortmund.inf.cw.surstwalat.client.util.TextRepository;
import java.util.Map;

/**
 * Start Hub
 *
 * @author Stephan Klimek
 */
public class StartHubPanel extends javax.swing.JPanel {

    Map<String, String> textRepository;

    /**
     * Creates new form StarterPanel
     */
    public StartHubPanel() {
        textRepository = TextRepository.getInstance().getTextRepository("ui_controls");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_startGame = new javax.swing.JButton();
        bt_editProfil = new javax.swing.JButton();
        bt_close = new javax.swing.JButton();
        lb_title = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 400));

        bt_startGame.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt_startGame.setActionCommand("bt_startGame");
        bt_startGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_startGame.setLabel(textRepository.get("start_game"));
        bt_startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_startGameActionPerformed(evt);
            }
        });

        bt_editProfil.setActionCommand("bt_editProfil");
        bt_editProfil.setLabel(textRepository.get("profil"));
        bt_editProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editProfilActionPerformed(evt);
            }
        });

        bt_close.setActionCommand("bt_close");
        bt_close.setLabel(textRepository.get("exit"));
        bt_close.setName(""); // NOI18N
        bt_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_closeActionPerformed(evt);
            }
        });

        lb_title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("FortDay");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_editProfil, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(bt_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(bt_startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(bt_startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(bt_editProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        bt_close.getAccessibleContext().setAccessibleName(textRepository.get("exit"));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_editProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editProfilActionPerformed
        MainFrame.getInstance().setFrame(new ProfilEditorPanel(), false);
    }//GEN-LAST:event_bt_editProfilActionPerformed

    private void bt_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeActionPerformed
        MainFrame.getInstance().dispose();
    }//GEN-LAST:event_bt_closeActionPerformed

    private void bt_startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_startGameActionPerformed
        MainFrame.getInstance().setFrame(new MainPanel(), false);
    }//GEN-LAST:event_bt_startGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_close;
    private javax.swing.JButton bt_editProfil;
    private javax.swing.JButton bt_startGame;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
